name: Build ghcr.io/JacobSanford/rtmp-multistream

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-push-images:
    uses: unb-libraries/dockworker/.github/workflows/build-push.yaml@6.x
    with:
      build-themes: false
      cleanup-old-images: false
      image-name: 'ghcr.io/jacobsanford/rtmp-multistream'
      push-all-branches: true
      push-branches: '[]'
    secrets:
      GH_CONTAINER_REGISTRY_USER: ${{ github.actor }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
