name: Test and Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validation-tests:
    name: Validation Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t rtmp-multistream:test .
    - name: Run validation tests
      run: bash tests/00_validation_tests.sh
    - name: Save Docker image
      run: docker save rtmp-multistream:test | gzip > rtmp-multistream-test.tar.gz
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: rtmp-multistream-test.tar.gz
        retention-days: 1

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: validation-tests
    steps:
    - uses: actions/checkout@v4
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Load Docker image
      run: gunzip -c rtmp-multistream-test.tar.gz | docker load
    - name: Run smoke tests
      run: bash tests/01_smoke_tests.sh

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: validation-tests
    steps:
    - uses: actions/checkout@v4
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Load Docker image
      run: gunzip -c rtmp-multistream-test.tar.gz | docker load
    - name: Run unit tests
      run: bash tests/02_unit_tests.sh

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: smoke-tests
    steps:
    - uses: actions/checkout@v4
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Load Docker image
      run: gunzip -c rtmp-multistream-test.tar.gz | docker load
    - name: Run integration tests
      run: bash tests/03_integration_tests.sh

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    needs: smoke-tests
    steps:
    - uses: actions/checkout@v4
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Load Docker image
      run: gunzip -c rtmp-multistream-test.tar.gz | docker load
    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
    - name: Run functional tests
      run: bash tests/04_functional_tests.sh

  build-push-images:
    name: Build and Push Image
    needs: [validation-tests, smoke-tests, unit-tests, integration-tests, functional-tests]
    uses: unb-libraries/dockworker/.github/workflows/build-push.yaml@6.x
    with:
      build-themes: false
      image-name: 'ghcr.io/jacobsanford/rtmp-multistream'
      push-all-branches: true
      push-branches: '[]'
    secrets:
      GH_CONTAINER_REGISTRY_USER: ${{ github.actor }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
